In [1]:
import numpy as np

In [3]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

A

array([-0.43143586,  1.06801516, -1.49855532, -0.78834401,  1.92828723,
        0.01880817,  0.06316484,  1.48136133, -0.11989096,  1.12826658])

In [8]:
B = np.random.randn(10)

B

array([ 0.42217094, -0.30275412, -2.98437258, -0.38025546,  1.93135111,
        0.04251812, -1.33921525,  0.06978144, -0.76635384, -0.92748368])

In [9]:
np.add(A,B )

array([-0.00926493,  0.76526103, -4.4829279 , -1.16859948,  3.85963833,
        0.06132629, -1.27605041,  1.55114278, -0.8862448 ,  0.2007829 ])

In [10]:
np.maximum(A,B)

array([ 0.42217094,  1.06801516, -1.49855532, -0.38025546,  1.93135111,
        0.04251812,  0.06316484,  1.48136133, -0.11989096,  1.12826658])

In [11]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True