In [25]:
import numpy as np

In [26]:
5/2

2.5

In [27]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
arr1 * arr1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [29]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

In [31]:
arr1 ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]])